"""Tests for sensor schema validation, range checks, and ingestion endpoints."""
from datetime import datetime, timezone, timedelta
from fastapi import status


def get_valid_packet():
    """Deterministic test fixture reflecting real ESP32 packet format."""
    return {
        "device_id": "ESP32_DEV_TEST01",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "IR": 27156,
        "RED": 18003,
        "Accel_X": 1056,
        "Accel_Y": 1152,
        "Accel_Z": 16428,
        "Gyro_X": -136,
        "Gyro_Y": 221,
        "Gyro_Z": 110,
        "Temp_F": 91.58,
        "GSR_Raw": 1911,
        "GSR_Voltage": 1.54,
    }


def test_ingest_valid_single_packet(client):
    packet = get_valid_packet()
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_201_CREATED
    data = response.json()
    assert data["success"] is True
    assert data["packets_ingested"] == 1
    assert data["device_id"] == "ESP32_DEV_TEST01"


def test_reject_negative_ir(client):
    packet = get_valid_packet()
    packet["IR"] = -50
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_zero_ir(client):
    packet = get_valid_packet()
    packet["IR"] = 0
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_unphysiological_temperature_high(client):
    packet = get_valid_packet()
    packet["Temp_F"] = 150.0  # Physically impossible for living human
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_unphysiological_temperature_low(client):
    packet = get_valid_packet()
    packet["Temp_F"] = 45.0  # Outside valid range
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_invalid_gsr_raw(client):
    packet = get_valid_packet()
    packet["GSR_Raw"] = 5000  # 12-bit max is 4095
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_invalid_gsr_voltage(client):
    packet = get_valid_packet()
    packet["GSR_Voltage"] = 5.0  # ESP32 3.3V max
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_reject_future_timestamp(client):
    packet = get_valid_packet()
    future_time = datetime.now(timezone.utc) + timedelta(hours=2)
    packet["timestamp"] = future_time.isoformat()
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_accept_esp32_formatted_timestamp(client):
    packet = get_valid_packet()
    # Format: "DD-MM-YYYY HH:MM:SS.mmm" as generated by ESP32 firmware
    now = datetime.now(timezone.utc)
    packet["timestamp"] = now.strftime("%d-%m-%Y %H:%M:%S.123")
    response = client.post("/api/v1/sensors/ingest", json=packet)
    assert response.status_code == status.HTTP_201_CREATED


def test_ingest_raw_esp32_csv_line(client):
    now = datetime.now(timezone.utc).strftime("%d-%m-%Y %H:%M:%S.500")
    csv_line = f"{now},27156,18003,1056,1152,16428,-136,221,110,91.58,1911,1.54"
    payload = {
        "device_id": "ESP32_DEV_CSV",
        "csv_line": csv_line,
    }
    response = client.post("/api/v1/sensors/ingest-csv", json=payload)
    assert response.status_code == status.HTTP_201_CREATED
    data = response.json()
    assert data["success"] is True
    assert data["packets_ingested"] == 1


def test_reject_malformed_csv_line(client):
    # Only 4 columns instead of 12
    payload = {
        "device_id": "ESP32_DEV_CSV",
        "csv_line": "13-09-2026 15:30:00,27156,18003,1056",
    }
    response = client.post("/api/v1/sensors/ingest-csv", json=payload)
    assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY


def test_ingest_batch(client):
    base_packet = get_valid_packet()
    batch = {
        "device_id": "ESP32_DEV_BATCH",
        "packets": [
            {**base_packet, "device_id": "ESP32_DEV_BATCH"},
            {**base_packet, "device_id": "ESP32_DEV_BATCH"},
            {**base_packet, "device_id": "ESP32_DEV_BATCH"},
        ],
    }
    response = client.post("/api/v1/sensors/ingest-batch", json=batch)
    assert response.status_code == status.HTTP_201_CREATED
    data = response.json()
    assert data["packets_ingested"] == 3
