"""add_notification_events_table

Revision ID: fd7051d87221
Revises: ec511392c977
Create Date: 2026-09-14 01:01:11.110339

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7051d87221'
down_revision: Union[str, None] = 'ec511392c977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('risk_event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trusted_contact_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_phone', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notification_level', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_category', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['trusted_contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_risk_event_id'), ['risk_event_id'], unique=True)
        batch_op.create_index('ix_notification_events_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_trusted_contact_id'), ['trusted_contact_id'], unique=False)
        batch_op.create_index('ix_notification_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_events_user_id'))
        batch_op.drop_index('ix_notification_events_user_created')
        batch_op.drop_index(batch_op.f('ix_notification_events_trusted_contact_id'))
        batch_op.drop_index('ix_notification_events_status')
        batch_op.drop_index(batch_op.f('ix_notification_events_risk_event_id'))
        batch_op.drop_index(batch_op.f('ix_notification_events_id'))
        batch_op.drop_index(batch_op.f('ix_notification_events_created_at'))

    op.drop_table('notification_events')
    # ### end Alembic commands ###
