"""add_youtube_video_cache_table

Revision ID: a9b8c7d6e5f4
Revises: fd7051d87221
Create Date: 2026-09-14 01:50:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b8c7d6e5f4'
down_revision: Union[str, None] = 'fd7051d87221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'youtube_video_cache',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('exercise_name', sa.String(length=100), nullable=False),
        sa.Column('video_id', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
        sa.Column('channel_title', sa.String(length=255), nullable=False),
        sa.Column('published_at', sa.String(length=50), nullable=True),
        sa.Column('youtube_url', sa.String(length=500), nullable=False),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtube_video_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_video_cache_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtube_video_cache_exercise_name'), ['exercise_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtube_video_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_youtube_video_cache_exercise_expires', ['exercise_name', 'expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_video_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_youtube_video_cache_exercise_expires')
        batch_op.drop_index(batch_op.f('ix_youtube_video_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_youtube_video_cache_exercise_name'))
        batch_op.drop_index(batch_op.f('ix_youtube_video_cache_id'))

    op.drop_table('youtube_video_cache')
    # ### end Alembic commands ###
