"""add_emotional_assessments_table

Revision ID: 0d10997bca32
Revises: ae52320ee072
Create Date: 2026-09-14 00:30:55.209343

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d10997bca32'
down_revision: Union[str, None] = 'ae52320ee072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotional_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('distress_level', sa.Integer(), nullable=False),
    sa.Column('llm_suggested_risk_level', sa.String(length=20), nullable=False),
    sa.Column('crisis_indicator', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotional_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotional_assessments_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_assessments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_assessments_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_emotional_assessments_msg_id', ['message_id'], unique=False)
        batch_op.create_index('ix_emotional_assessments_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotional_assessments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emotional_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_user_id'))
        batch_op.drop_index('ix_emotional_assessments_user_created')
        batch_op.drop_index('ix_emotional_assessments_msg_id')
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_message_id'))
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_id'))
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_created_at'))
        batch_op.drop_index(batch_op.f('ix_emotional_assessments_conversation_id'))

    op.drop_table('emotional_assessments')
    # ### end Alembic commands ###
