"""add_risk_events_table

Revision ID: c106d634d9e8
Revises: 0d10997bca32
Create Date: 2026-09-14 00:40:44.278976

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c106d634d9e8'
down_revision: Union[str, None] = '0d10997bca32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reason_category', sa.String(length=100), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('trusted_contact_notified', sa.Boolean(), nullable=False),
    sa.Column('notification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['emotional_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_id'), ['id'], unique=False)
        batch_op.create_index('ix_risk_events_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_user_id'))
        batch_op.drop_index('ix_risk_events_user_created')
        batch_op.drop_index(batch_op.f('ix_risk_events_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_risk_events_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_assessment_id'))

    op.drop_table('risk_events')
    # ### end Alembic commands ###
