"""add_trusted_contacts_table

Revision ID: ec511392c977
Revises: c106d634d9e8
Create Date: 2026-09-14 00:50:37.100801

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec511392c977'
down_revision: Union[str, None] = 'c106d634d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('notification_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trusted_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trusted_contacts_id'), ['id'], unique=False)
        batch_op.create_index('ix_trusted_contacts_user_enabled', ['user_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_trusted_contacts_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trusted_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trusted_contacts_user_id'))
        batch_op.drop_index('ix_trusted_contacts_user_enabled')
        batch_op.drop_index(batch_op.f('ix_trusted_contacts_id'))

    op.drop_table('trusted_contacts')
    # ### end Alembic commands ###
