"""initial_canonical_schema

Revision ID: e8a9641b1b1d
Revises: 
Create Date: 2026-09-13 15:41:24.850604

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a9641b1b1d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'CONNECTING', 'CONNECTED', 'NO_DATA', 'STALE', 'DISCONNECTED', 'ERROR', name='devicestatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('last_packet_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_valid_packet_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_transport', sa.String(length=20), nullable=True),
    sa.Column('total_packets_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_packets_accepted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_packets_rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_devices_user_id_status', ['user_id', 'status'], unique=False)

    op.create_table('processed_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=True),
    sa.Column('hrv_sdnn_ms', sa.Float(), nullable=True),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('skin_conductance_us', sa.Float(), nullable=True),
    sa.Column('motion_magnitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_metrics_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_processed_metrics_device_timestamp', ['device_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('sensor_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_batches_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sensor_batches_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_batches_id'), ['id'], unique=False)

    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('transport', sa.String(length=20), server_default='HTTP', nullable=False),
    sa.Column('quality', sa.String(length=20), server_default='GOOD', nullable=False),
    sa.Column('ir', sa.Integer(), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('accel_x', sa.Integer(), nullable=False),
    sa.Column('accel_y', sa.Integer(), nullable=False),
    sa.Column('accel_z', sa.Integer(), nullable=False),
    sa.Column('gyro_x', sa.Integer(), nullable=False),
    sa.Column('gyro_y', sa.Integer(), nullable=False),
    sa.Column('gyro_z', sa.Integer(), nullable=False),
    sa.Column('temp_f', sa.Float(), nullable=False),
    sa.Column('gsr_raw', sa.Integer(), nullable=False),
    sa.Column('gsr_voltage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_sensor_data_device_received_at', ['device_id', 'received_at'], unique=False)
        batch_op.create_index('ix_sensor_data_device_sensor_ts', ['device_id', 'sensor_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_sensor_timestamp'), ['sensor_timestamp'], unique=False)

    op.create_table('stress_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stress_level', sa.String(length=50), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stress_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_predictions_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_stress_predictions_device_timestamp', ['device_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_stress_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stress_predictions_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_predictions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stress_predictions_id'))
        batch_op.drop_index('ix_stress_predictions_device_timestamp')
        batch_op.drop_index(batch_op.f('ix_stress_predictions_device_id'))

    op.drop_table('stress_predictions')
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_sensor_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_received_at'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_id'))
        batch_op.drop_index('ix_sensor_data_device_sensor_ts')
        batch_op.drop_index('ix_sensor_data_device_received_at')
        batch_op.drop_index(batch_op.f('ix_sensor_data_device_id'))

    op.drop_table('sensor_data')
    with op.batch_alter_table('sensor_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_batches_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_batches_device_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_batches_batch_id'))

    op.drop_table('sensor_batches')
    with op.batch_alter_table('processed_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_metrics_timestamp'))
        batch_op.drop_index(batch_op.f('ix_processed_metrics_id'))
        batch_op.drop_index('ix_processed_metrics_device_timestamp')
        batch_op.drop_index(batch_op.f('ix_processed_metrics_device_id'))

    op.drop_table('processed_metrics')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_user_id_status')
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_last_seen'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
