"""Sensor packet schemas with strict physiological validation and canonical normalization.

Directly maps and normalizes the 12 fields generated by the ESP32 firmware:
Timestamp, IR, RED, Accel_X, Accel_Y, Accel_Z, Gyro_X, Gyro_Y, Gyro_Z, Temp_F, GSR_Raw, GSR_Voltage
"""
import math
import re
from datetime import datetime, timezone, timedelta
from enum import Enum
from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field, field_validator, model_validator


class SensorQuality(str, Enum):
    """Quality grading of real physiological sensor signals."""
    GOOD = "GOOD"        # Proper skin contact, valid optical pulsatility, normal GSR/Temp
    FAIR = "FAIR"        # Weak optical contact or borderline skin temperature
    POOR = "POOR"        # Lead-off detected, extreme noise or GSR rail saturation
    INVALID = "INVALID"  # Unphysiological out-of-bounds numbers, NaN, or Inf


class SensorTransport(str, Enum):
    """Ingestion transport mechanism."""
    SERIAL = "SERIAL"
    HTTP = "HTTP"
    WIFI = "WIFI"


def parse_flexible_timestamp(val: Union[datetime, str, int, float]) -> datetime:
    """Parses various timestamp formats emitted by ESP32 or gateways."""
    if isinstance(val, datetime):
        if val.tzinfo is None:
            return val.replace(tzinfo=timezone.utc)
        return val.astimezone(timezone.utc)

    if isinstance(val, (int, float)):
        if math.isnan(val) or math.isinf(val):
            raise ValueError("Timestamp cannot be NaN or Infinity")
        if val > 1e11:  # Milliseconds
            return datetime.fromtimestamp(val / 1000.0, tz=timezone.utc)
        return datetime.fromtimestamp(val, tz=timezone.utc)

    if isinstance(val, str):
        val = val.strip()

        # Handle numeric string (epoch ms or s)
        if val.isdigit():
            num = int(val)
            if num > 1e11:
                return datetime.fromtimestamp(num / 1000.0, tz=timezone.utc)
            elif num > 1e8:
                return datetime.fromtimestamp(num, tz=timezone.utc)
            else:
                # Relative millis counter from ESP32 boot without NTP sync
                return datetime.now(timezone.utc)

        # Format: "DD-MM-YYYY HH:MM:SS.mmm" or "DD-MM-YYYY HH:MM:SS"
        # As declared in ESP32 firmware: const char* tzInfo = "IST-5:30";
        esp32_pattern = r"^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?$"
        match = re.match(esp32_pattern, val)
        if match:
            day, month, year, hour, minute, second, frac = match.groups()
            microsecond = int(frac.ljust(6, '0')[:6]) if frac else 0
            ist_tz = timezone(timedelta(hours=5, minutes=30))
            dt = datetime(
                int(year), int(month), int(day),
                int(hour), int(minute), int(second),
                microsecond,
                tzinfo=ist_tz
            )
            return dt.astimezone(timezone.utc)

        # ISO 8601 fallback
        try:
            dt = datetime.fromisoformat(val.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt.astimezone(timezone.utc)
        except ValueError:
            pass

    raise ValueError(f"Unrecognized timestamp format: '{val}'")


def evaluate_sensor_quality(
    ir: int,
    red: int,
    temp_f: float,
    gsr_voltage: float,
) -> SensorQuality:
    """Evaluates data quality based on physical sensor characteristics."""
    # 1. Invalid checks
    if any(math.isnan(v) or math.isinf(v) for v in [temp_f, gsr_voltage]):
        return SensorQuality.INVALID
    if ir <= 0 or red <= 0 or temp_f < 60.0 or temp_f > 120.0 or gsr_voltage < 0.0 or gsr_voltage > 3.4:
        return SensorQuality.INVALID

    # 2. Poor checks (sensor lead-off or rail saturation)
    if ir < 1000 or red < 1000:
        return SensorQuality.POOR
    if gsr_voltage < 0.05 or gsr_voltage > 3.25:
        return SensorQuality.POOR

    # 3. Fair checks (low optical amplitude or cold extremities)
    if ir < 5000 or red < 5000 or temp_f < 72.0:
        return SensorQuality.FAIR

    return SensorQuality.GOOD


class CanonicalSensorPacket(BaseModel):
    """Canonical sensor packet representing the authoritative internal format.

    Transport-agnostic: both USB Serial and HTTP/Wi-Fi normalize to this schema.
    """
    device_id: str = Field(default="SANJEEVNI-ESP32-001", min_length=2, max_length=100, description="Unique hardware identifier")
    sensor_timestamp: Union[datetime, str, int, float] = Field(
        ...,
        alias="timestamp",
        description="Preserved ESP32 original sensor timestamp"
    )
    received_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Backend reception timestamp in UTC"
    )
    sequence_number: Optional[int] = Field(
        None,
        ge=0,
        description="Optional packet counter if emitted by firmware"
    )

    # Photoplethysmography (PPG) & HR/SpO2
    heart_rate: Optional[int] = Field(None, description="Calculated heart rate in BPM")
    valid_heart_rate: Optional[int] = Field(None, description="1 if heart rate reading is valid, 0 otherwise")
    spo2: Optional[int] = Field(None, description="Calculated blood oxygen saturation %")
    valid_spo2: Optional[int] = Field(None, description="1 if SpO2 reading is valid, 0 otherwise")

    ir: int = Field(..., alias="IR", description="Infrared raw photodiode ADC count")
    red: int = Field(..., alias="RED", description="Red raw photodiode ADC count")

    # Accelerometer - MPU6050 (Supports raw counts or float g)
    accel_x: float = Field(..., alias="Accel_X", description="X-axis acceleration")
    accel_y: float = Field(..., alias="Accel_Y", description="Y-axis acceleration")
    accel_z: float = Field(..., alias="Accel_Z", description="Z-axis acceleration")

    # Gyroscope - MPU6050 (Supports raw counts or float dps)
    gyro_x: float = Field(..., alias="Gyro_X", description="X-axis gyroscope")
    gyro_y: float = Field(..., alias="Gyro_Y", description="Y-axis gyroscope")
    gyro_z: float = Field(..., alias="Gyro_Z", description="Z-axis gyroscope")

    # Body Temperature - ClosedCube MAX30205 (°F)
    temperature: float = Field(..., alias="Temp_F", description="Skin temperature in Fahrenheit")

    # Galvanic Skin Response (GSR) - ESP32 12-bit ADC
    gsr_raw: int = Field(..., alias="GSR_Raw", description="Raw 12-bit ADC value (0-4095)")
    gsr_voltage: float = Field(..., alias="GSR_Voltage", description="Calculated GSR voltage in Volts (0.0-3.3)")

    transport: SensorTransport = Field(
        default=SensorTransport.HTTP,
        description="Transport used: SERIAL, HTTP, or WIFI"
    )
    quality: Optional[SensorQuality] = Field(
        None,
        description="Evaluated sensor quality (GOOD, FAIR, POOR, INVALID)"
    )

    model_config = {
        "populate_by_name": True,
        "json_schema_extra": {
            "example": {
                "device_id": "SANJEEVNI-ESP32-001",
                "sensor_timestamp": "2026-09-16T20:26:52.887Z",
                "sequence_number": 980,
                "heart_rate": 136,
                "valid_heart_rate": 1,
                "spo2": 99,
                "valid_spo2": 1,
                "ir": 76991,
                "red": 129006,
                "accel_x": -0.082092,
                "accel_y": 0.696716,
                "accel_z": -0.767517,
                "gyro_x": 6.763359,
                "gyro_y": -1.366412,
                "gyro_z": -0.832061,
                "Temp_F": 95.9,
                "gsr_raw": 0,
                "gsr_voltage": 0.0
            }
        }
    }

    @field_validator("sensor_timestamp")
    @classmethod
    def validate_sensor_timestamp(cls, v: Union[datetime, str, int, float]) -> datetime:
        dt = parse_flexible_timestamp(v)
        now = datetime.now(timezone.utc)
        # Reject future timestamps (> 5 minutes in future)
        if dt > now + timedelta(minutes=5):
            raise ValueError(f"Packet timestamp {dt} is in the future relative to server time {now}")
        # Reject ancient timestamps (> 60 days)
        if dt < now - timedelta(days=60):
            raise ValueError(f"Packet timestamp {dt} is older than 60 days")
        return dt

    @field_validator("ir", "red")
    @classmethod
    def validate_optical_ppg(cls, v: int, info) -> int:
        if math.isnan(v) or math.isinf(v):
            raise ValueError(f"{info.field_name} cannot be NaN or Infinity")
        if v <= 0:
            raise ValueError(f"{info.field_name.upper()} value must be positive (received {v})")
        if v > 300000:
            raise ValueError(f"{info.field_name.upper()} value exceeds MAX30102 saturation limit (received {v})")
        return v

    @field_validator("temperature")
    @classmethod
    def validate_temperature(cls, v: float) -> float:
        if math.isnan(v) or math.isinf(v):
            raise ValueError("Temperature cannot be NaN or Infinity")
        if v < 60.0 or v > 120.0:
            raise ValueError(f"Temperature {v}°F is outside valid physiological range (60.0°F - 120.0°F)")
        return round(v, 2)

    @field_validator("gsr_raw")
    @classmethod
    def validate_gsr_raw(cls, v: int) -> int:
        if math.isnan(v) or math.isinf(v):
            raise ValueError("GSR raw cannot be NaN or Infinity")
        if v < 0 or v > 4095:
            raise ValueError(f"GSR raw ADC reading {v} is outside ESP32 12-bit range (0 - 4095)")
        return v

    @field_validator("gsr_voltage")
    @classmethod
    def validate_gsr_voltage(cls, v: float) -> float:
        if math.isnan(v) or math.isinf(v):
            raise ValueError("GSR voltage cannot be NaN or Infinity")
        if v < 0.0 or v > 3.4:
            raise ValueError(f"GSR voltage {v}V is outside ESP32 voltage range (0.0V - 3.3V)")
        return round(v, 3)

    @field_validator("accel_x", "accel_y", "accel_z", "gyro_x", "gyro_y", "gyro_z")
    @classmethod
    def validate_motion_ranges(cls, v: float, info) -> float:
        if math.isnan(v) or math.isinf(v):
            raise ValueError(f"{info.field_name} cannot be NaN or Infinity")
        return v

    @model_validator(mode="after")
    def compute_quality(self) -> "CanonicalSensorPacket":
        if self.quality is None:
            self.quality = evaluate_sensor_quality(
                ir=self.ir,
                red=self.red,
                temp_f=self.temperature,
                gsr_voltage=self.gsr_voltage,
            )
        return self


# Backward-compatibility alias for RawSensorPacket
RawSensorPacket = CanonicalSensorPacket


class SensorBatchPayload(BaseModel):
    """Batched sensor telemetry request payload sent by ESP32 firmware (~5 readings per POST)."""
    device_id: Optional[str] = Field(None, description="Outer hardware device identifier")
    transport: Optional[Union[SensorTransport, str]] = Field(default=SensorTransport.HTTP, description="Ingestion transport mechanism")
    readings: Optional[List[CanonicalSensorPacket]] = Field(None, description="List of batched real sensor readings")
    packets: Optional[List[CanonicalSensorPacket]] = Field(None, description="Alternative list alias for batched readings")

    model_config = {
        "populate_by_name": True
    }


class SensorBatchPacket(BaseModel):
    """Batch packet ingestion schema."""
    device_id: str = Field(..., description="Device ID sending this batch")
    packets: List[CanonicalSensorPacket] = Field(..., min_length=1, max_length=1500)


class RawCSVLinePayload(BaseModel):
    """Direct CSV line ingestion from ESP32 serial or BLE bridge."""
    device_id: str
    csv_line: str = Field(
        ...,
        description="CSV string matching ESP32 output: Timestamp,IR,RED,Accel_X,Accel_Y,Accel_Z,Gyro_X,Gyro_Y,Gyro_Z,Temp_F,GSR_Raw,GSR_Voltage"
    )


class SensorIngestResponse(BaseModel):
    """Authoritative response payload for sensor ingestion."""
    status: str = "success"
    accepted: bool = True
    success: bool = True
    device_id: str
    received: int = 1
    latest_sequence_number: Optional[int] = None
    received_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    sensor_timestamp: Optional[datetime] = None
    quality: SensorQuality = SensorQuality.GOOD
    is_duplicate: bool = False
    is_out_of_order: bool = False
    packets_received: int = 1
    packets_ingested: int = 1
    sampling_rate_hz: Optional[float] = None
    message: str = "Sensor telemetry validated and updated in live memory cache"

